version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/deploy
hooks:
  BeforeInstall:
    - location: install_dependencies
      timeout: 300
      runas: ec2-user
    - location: start_server
      timeout: 300
      runas: ec2-user